"""schema final

Revision ID: 34ef4c51645d
Revises: 
Create Date: 2026-08-26 21:00:10.199655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ef4c51645d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client', sa.String(length=120), nullable=False),
    sa.Column('localisation', sa.String(length=120), nullable=False),
    sa.Column('type_intervention', sa.String(length=60), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('priorite', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('token_suivi', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_suivi')
    )
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('seuil_alerte', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('technicien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('specialite', sa.String(length=200), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('derniere_position', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('date_planifiee', sa.Date(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('rapport', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demande.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['technicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technicien_id'], ['technicien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisation_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisation_piece')
    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('intervention')
    op.drop_table('technicien')
    op.drop_table('piece')
    op.drop_table('demande')
    # ### end Alembic commands ###
